name: Build Windows

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-x64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Install dependencies
      run: pnpm install
    - name: Build x64
      run: pnpm build:win --x64
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload x64 installer artifact
      uses: actions/upload-artifact@v4
      with:
        name: betterx-windows-x64-installer
        path: dist/*-Setup-*.exe
        compression-level: 0
        if-no-files-found: error
    - name: Upload x64 portable artifact
      uses: actions/upload-artifact@v4
      with:
        name: betterx-windows-x64-portable
        path: dist/*-portable.exe
        compression-level: 0
        if-no-files-found: error

  build-arm64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Install dependencies
      run: pnpm install
    - name: Build ARM64
      run: pnpm build:win --arm64
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload ARM64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: betterx-windows-arm64
        path: dist/*-arm64.exe
        compression-level: 0
        if-no-files-found: error
