name: Build macOS

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-intel:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install bun
      uses: oven-sh/setup-bun@v1
      with:
        version: 8
    - name: Install dependencies
      run: bun install
    - name: Build Intel
      run: bun build:mac --x64
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Intel artifact
      uses: actions/upload-artifact@v4
      with:
        name: betterx-mac-intel
        path: dist/*-x64.dmg
        compression-level: 0
        if-no-files-found: error

  build-arm:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install bun
      uses: oven-sh/setup-bun@v1
      with:
        version: 8
    - name: Install dependencies
      run: bun install
    - name: Build ARM
      run: bun build:mac --arm64
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload ARM artifact
      uses: actions/upload-artifact@v4
      with:
        name: betterx-mac-arm
        path: dist/*-arm64.dmg
        compression-level: 0
        if-no-files-found: error
