name: Build macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-intel:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Install dependencies
      run: pnpm install
    - name: Build Intel
      run: pnpm build:mac --x64
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Intel artifact
      uses: actions/upload-artifact@v4
      with:
        name: mac-intel-build
        path: dist/*-x64.dmg

  build-arm:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Install dependencies
      run: pnpm install
    - name: Build ARM
      run: pnpm build:mac --arm64
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload ARM artifact
      uses: actions/upload-artifact@v4
      with:
        name: mac-arm-build
        path: dist/*-arm64.dmg
