name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci

    - name: Install Wine
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y wine32

    - name: Build for Windows
      run: npm run build:win

    - name: Build for Linux (deb)
      run: npm run build -- --linux deb

    - name: Build for Linux (AppImage)
      run: npm run build -- --linux AppImage

    - name: Build for Linux (snap)
      run: npm run build -- --linux snap

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.ref }}
        release_name: Release v${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Windows Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/betterx-desktop-${{ github.ref }}-win.exe
        asset_name: betterx-desktop-${{ github.ref }}-win.exe
        asset_content_type: application/exe

    - name: Upload Linux (deb) Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/betterx-desktop-${{ github.ref }}-linux.deb
        asset_name: betterx-desktop-${{ github.ref }}-linux.deb
        asset_content_type: application/vnd.debian.binary-package

    - name: Upload Linux (AppImage) Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/betterx-desktop-${{ github.ref }}-linux.AppImage
        asset_name: betterx-desktop-${{ github.ref }}-linux.AppImage
        asset_content_type: application/octet-stream

    - name: Upload Linux (snap) Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/betterx-desktop-${{ github.ref }}-linux.snap
        asset_name: betterx-desktop-${{ github.ref }}-linux.snap
        asset_content_type: application/octet-stream
