name: Build for Multiple Platforms and Push to Branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install system dependencies and Wine
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y wine64 wine32 snapcraft
        sudo snap install --classic snapcraft

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install project dependencies
      run: pnpm install

    - name: Build for Windows
      run: pnpm run build:win

    - name: Build for Linux (DEB)
      run: pnpm run build:linux-deb

    - name: Build for Linux (AppImage)
      run: pnpm run build:linux-appimage

    - name: Build for Linux (Snap)
      run: |
        snapcraft
        mv *.snap dist/

    - name: Create build branch
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git checkout -b build-${{ github.run_number }}

    - name: Move build artifacts
      run: |
        mkdir -p builds
        mv dist/* builds/

    - name: Commit and push to build branch
      run: |
        git add builds
        git commit -m "Add build artifacts for run ${{ github.run_number }}"
        git push origin build-${{ github.run_number }}
